import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "./globals.css";


export const metadata: Metadata = {
  title: "MultiForm",
  description: "Generated by create next app",
};

const karla = Karla({
  subsets: ['latin'],
  weight: ['400', '700'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${karla.className} antialiased bg-sky`}
      >
        {children}
      </body>
    </html>
  );
}
